const fs = require('fs');
const path = require('path');
const routerinfo = require('./routerinfo');


module.exports = {	
	"nd":function(req,res,filename){
		/*
		let basename = path.basename(filename,".nd");		
		routerinfo[basename](req,res);		
		*/
		routerinfo[path.basename(filename,".nd")](req,res);
	},
	"html":function(req,res,filename){
		res.statusCode=200;
		res.setHeader("Content-type","text/html;charset=utf-8");
		fs.readFile(filename,(err,data)=>{
			if(err){
				res.write(err);
				res.end();
			}else{
				res.write(data);
				res.end();
			}
		});
	},
	"css":function(req,res,filename){
		res.statusCode=200;
		res.setHeader("Content-type","text/css;charset=utf-8");
		fs.readFile(filename,(err,data)=>{
			if(err){
				res.write(err);
				res.end();
			}else{
				res.write(data);
				res.end();
			}
		});
	},
	"js":function(req,res,filename){
		res.statusCode=200;
		res.setHeader("Content-type","application/x-javascript;charset=utf-8");
		fs.readFile(filename,(err,data)=>{
			if(err){
				res.write(err);
				res.end();
			}else{
				res.write(data);
				res.end();
			}
		});
	},
    "json":function(req,res,filename){
        res.statusCode=200;
        res.setHeader("Content-type","text/json","charset=utf-8");
        fs.readFile(filename,(err,data)=>{
            if(err){
                res.write(err);
                res.end();
            }else{
                res.write(data);
                res.end();
            }
        });
    },
	"jpg":function(req,res,filename){
		res.statusCode=200;
		res.setHeader("Content-type","binary","image/jpeg");
		fs.readFile(filename,(err,data)=>{
			if(err){
				res.write(err);
				res.end();
			}else{
				res.write(data,"binary");
				res.end();
			}
		});
	},
    "png":function(req,res,filename){
        res.statusCode=200;
        res.setHeader("Content-type","binary","image/png");
        fs.readFile(filename,(err,data)=>{
            if(err){
                res.write(err);
                res.end();
            }else{
                res.write(data,"binary");
                res.end();
            }
        });
    },
	"error":function(req,res){
		res.statusCode=404;
		res.setHeader("Content-type","text/html;charset=utf-8");
		res.write("出错了");
		res.end();
	}
}
